### ISSUE TITLE
IndexError on .hexdigest()

### ISSUE THREAD

**Issue by TiiFuchs** [jdswinbank/treehash#2] opened 2016-10-03 18:15 UTC
Hi I'm downloading a bunch of files from AWS Glacier and check against the SHA256TreeHash but on a few files I get a IndexError:

```
  File "./download-archive.py", line 108, in download_archives
    calculated_hash = hash_calculator.hexdigest()
  File "/home/ec2-user/aws/.venv/local/lib/python2.7/site-packages/treehash/treehash.py", line 51, in hexdigest
    return self._compute_hash().hexdigest()
  File "/home/ec2-user/aws/.venv/local/lib/python2.7/site-packages/treehash/treehash.py", line 32, in _compute_hash
    return recursive_hash(to_recurse)
  File "/home/ec2-user/aws/.venv/local/lib/python2.7/site-packages/treehash/treehash.py", line 25, in recursive_hash
    return output[0]
IndexError: list index out of range
```

When exactly does this get raised? What can I do against that?

**Comment by TiiFuchs** [comment] 2016-10-03 18:25
I will just assume, that an IndexError means that the hash text is incorrect and the file needs to be downloaded again.

**Comment by jdswinbank** [comment] 2016-10-03 18:32
That clearly shouldn't happen, but I don't immediately see the cause.

How are you constructing the hash calculator? That is, what does the line

```
hash_calculator = ...
```

look like?

**Comment by jdswinbank** [comment] 2016-10-03 18:38
Wait, my mistake.

This is fixed in the current github version, but I've never got around to pushing that to pypi. I'll take care of that now.

**Comment by jdswinbank** [comment] 2016-10-03 18:44
Release 1.0.2 tagged & pushed to pypi. I think that should solve this issue. Please reopen if you're still having problems.

**Closed as completed by jdswinbank** 2016-10-03 18:44 UTC
